### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by rondhi** [izzy/twitch-chat#1]
I have a few feature requests.

- Ability to hide bot messages
- Ability to hide commands
- Ability to display larger emotes
- Fade messages after time

**Comment by andi242** [comment]
I made a fork of this repo to adapt it to my personal needs/style and still give credit to izzy.
I did a few of your requests (bots, commands, fade). Feel free to have a look. https://github.com/andi242/twitch-chat

**Comment by izzy** [comment]
@andi242 I've seen your fork and will try to reincorporate those changes as generalized as possible(since it's such a small project I don't think it would help too much to have a lot of forks).

I especially like the documentation work on the README, I've been wanting to find some time to do a better job at that and yours looks a lot cleaner and more readable.

**Comment by andi242** [comment]
@izzy thanks!
I just not wanted to take your work without credit, since I think the idea is just incredible!
At the same time I had a different need for design, config, etc. and I did not want to flood you with requests ;-)

**Comment by izzy** [comment]
I've implemented all of the features @rondhi requested.

Thanks to @andi242 for providing some of the work in his fork.
